sudo: true

service:
  docker

before-install:
  - docker-compose up -d --build
  - docker images

scripts:
  - cd test && sh app-action.sh && cd -
  - cd test && sh remove-task.sh && cd -

after_script:
  - docker push praveenjindal62/pyapp:latest
  - docker push praveenjindal62/nginx:latest
  - docker search praveenjindal62

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  region: "us-east-1"
  app: "WebApp2"
  env: "Webapp2-env"
  bucket_name: "elasticbeanstalk-us-east-1-415624473279"
  on:
    branch: master
