version: "3"
services:

  pyapp:
    build: 
      context: ./webapp
      dockerfile: Dockerfile
    image: app_pyapp:latest 
    depends_on:
      - dbapp
    environment:
      MONGOURL: dbapp:27017
      FLASK_PORT: 5004
    deploy:
      replicas: 10
    networks: 
      - backend

  dbapp:
    build:
      context: ./mongo
      dockerfile: Dockerfile
    image: app_dbapp:latest
    networks: 
      - backend

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: app_nginx:latest
    ports: 
      - "8080:80"
    depends_on:
      - pyapp
    environment:
      APPURL: pyapp
      APPPORT: 5004
    networks: 
      - backend

networks:
  backend: 

